export const SET_MEETINGS_DATA = 'SET_FRONTOWNIA_MEETINGS_DATA';
export const CLEAR_MEETINGS_DATA = 'CLEAR_FRONTOWNIA_MEETINGS_DATA';
export const FETCH_MEETINGS_DATA = 'FETCH_FRONTOWNIA_MEETINGS_DATA';

export const PAGE_LOAD_COMPLETED_STATUS = 'complete';
export const LOG_USER_VISITED_PAGE = 'LOG_USER_VISITED_PAGE ';