export const SET_MEETINGS_DATA = 'SET_FRONTOWNIA_MEETINGS_DATA';
export const CLEAR_MEETINGS_DATA = 'CLEAR_FRONTOWNIA_MEETINGS_DATA';
export const FETCH_MEETINGS_DATA = 'FETCH_FRONTOWNIA_MEETINGS_DATA';